services:
  deno:
    build:
      context: ./deno
    environment:
      - FLAG=ictf{cl_54y5_570p_bu7_73_54y5_60_60_60}
  flask:
    build:
      context: ./flask
  proxy:
    build:
      context: ./proxy
    environment:
      - FLASK_HOST=flask
      - FLASK_PORT=4001
      - DENO_HOST=deno
      - DENO_PORT=4002
    ports:
      - 4000:4000